import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

import NFT from '../../../hardhat/artifacts/contracts/NFT.sol/NFT.json';
import Marketplace from '../../../hardhat/artifacts/contracts/NFTMarketplace.sol/NFTMarketplace.json';

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Tickets Token MarketPlace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1>Home</h1>
      </main>
    </>
  );
};

export default Home;
